# Generated by Django 4.2.14 on 2024-08-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.FloatField()),
                ('breed', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('neutered', models.BooleanField(default=False)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_area', models.CharField(choices=[('eye', 'Eye'), ('skin', 'Skin')], max_length=50)),
                ('photo', models.ImageField(upload_to='diagnosis_photos/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convetingBE.pet')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_disease', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convetingBE.diagnosissubmission')),
            ],
        ),
    ]
