# Generated by Django 5.1 on 2024-09-05 02:04

import convetingBE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convetingBE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomdescription',
            name='photo',
            field=models.ImageField(upload_to=convetingBE.models.diag_img_upload),
        ),
    ]
