# Generated by Django 4.2.14 on 2024-08-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convetingBE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='disease',
            field=models.ForeignKey(db_column='disease', on_delete=django.db.models.deletion.DO_NOTHING, to='convetingBE.disease'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='seq',
            field=models.ForeignKey(db_column='seq', on_delete=django.db.models.deletion.CASCADE, to='convetingBE.symptomdescription'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='disease',
            field=models.CharField(db_column='disease', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='seq',
            field=models.OneToOneField(db_column='seq', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='convetingBE.symptomdescription'),
        ),
        migrations.AlterField(
            model_name='symptomdescription',
            name='seq',
            field=models.PositiveIntegerField(db_column='seq', primary_key=True, serialize=False),
        ),
    ]
