# Generated by Django 5.1 on 2024-08-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convetingBE', '0002_remove_prediction_eye10_remove_prediction_eye11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cure',
            field=models.TextField(default='Nothing', max_length=500),
        ),
    ]
