# Generated by Django 5.1 on 2024-08-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convetingBE', '0003_disease_cure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomdescription',
            name='part',
            field=models.CharField(max_length=20),
        ),
    ]
